[41기 김광휘] Assignment 1 | Westagram Backend Project - Express 초기 환경세팅
wecode-bootcamp-korea/41-backend-westagram-2 pull request #1
Opened 2022-12-20 04:45 UTC by Hwi227

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- email, password를 이용한 로그인 기능 구현 (예시)

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- API 호출 시 필요한 값들에 대한 유효성 검사 (예시)

<br />

## :: 테스트 결과 이미지
1. Server가 잘 동작하는지 확인할 수 있는 Terminal 캡쳐 이미지
2. Postman(Client Tool)을 이용한 API 테스트 결과 이미지
3. DB 작업 PR인 경우 Table 생성 및 수정 결과에 대해 확인할 수 있는 이미지

<br />

## :: 기타 질문 및 특이 사항
- 제가 작성한 함수의 로직이 너무 복잡하다고 생각이 됩니다. 더 효율적인 방법이 없을까요? (예시)

2022-12-20 10:31 UTC, Jon9Beom commented on kwanghwi/myapp/.env sample
> +PORT = YOUR PORT NUMBER SHOULD BE HERE!
- dbmate 연결 목적의 DATABASE_URL이 작성될 필요가 있습니다. 또한 여기에는 개인이 로컬 환경에서 어떠한 rdbms를 쓰는지 그 힌트가 될 수 있는 단어와, 포트번호를 지우고 중의적인 단어를 대신 사용해주세요.
- dbmate는 migration file을 생성 및 적용 등 database 이력 관리를 위한 도구라고 생각하시면 좋을 것 같습니다.
- git을 통해 백엔드 api서버에 대한 소스 코드가 이력관리가 되듯이, database도 git을 통해 그동안 어떤 수정 사항이 있었는지 migration file들을 통해 확인 할 수 있습니다.
- 뿐만 아니라 migration 파일을 공유함으로서 백엔드 개발자간 협업을 할 때, 모두가 완전히 똑같은 구조의 database를 가질 수 있게 됩니다.
    
    ```jsx
    // Example	
    
    DATABASE_URL="rdbmsType://username:password@iphost:portNumber/databaseName"
    ```

2022-12-20 10:31 UTC, Jon9Beom commented on kwanghwi/myapp/.env sample
> +TYPEORM_HOST = 127.0.0.1
```suggestion
TYPEORM_HOST = localhost
```
OS에 따라 혹은 경우에 따라 localhost는 127.0.0.1이 아닌 경우도 있기 때문에 localhost라고 수정해주세요~

2022-12-20 10:31 UTC, Jon9Beom commented on kwanghwi/myapp/.env sample
> +TYPEORM_USERNAME = root
```suggestion
TYPEORM_USERNAME = username
```

2022-12-20 10:31 UTC, Jon9Beom commented on kwanghwi/myapp/.env sample
> +TYPEORM_PORT = 3306
```suggestion
TYPEORM_PORT = dbPort
```
3306은 mysql 고유의 port number입니다. 다른것을 중의정으로 썻다고 하더라도 3306을 그대로 작성하게 되면 rdbms중에서도 mysql을 쓴다는 것을 간접적으로 알 수 있게 됩니다.

2022-12-20 10:31 UTC, Jon9Beom commented on kwanghwi/myapp/app.js
> +  });
- myDataSource 보다는 `appDataSource` , `mysqlDataSource` 혹은 간결하게 `database`로 변수명을 변경해주세요. “my”라는 용어는 예제 코드에서는 사용할 수 있으나 실제 코드에서는 피해주세요.

2022-12-20 10:31 UTC, Jon9Beom commented on kwanghwi/myapp/app.js
> +// http -v GET 127.0.0.1:3000/ping
- 불필요한 주석은 삭제해주세요!
- 코드에 대한 설명을 주석으로 남겨놓고 싶어서 주석을 달게 되는 것은 처음에는 좋아보일 수는 있으나 나중에 코드에 수정이 발생했을 때 설명하는 주석까지 같이 수정하는 것을 놓치게 된다면 결국 설명 주석과 코드의 내용이 달라지고 오히려 더 유지보수하기 힘들게 될 수 있습니다.
- 주석으로 코드를 설명하기보다는 코드 자체의 가독성이 좋게만들어서 부가적인 설명이 필요없는 코드로 만들어주세요!

2022-12-20 10:31 UTC, Jon9Beom commented on kwanghwi/myapp/app.js
> +//const server = http.createServer(app);
```suggestion
```

2022-12-20 10:31 UTC, Jon9Beom commented on kwanghwi/myapp/app.js
> +  res.status(200).json({ message: "pong" });
```suggestion
  return res.status(200).json({ message: "pong" });
```
화살표 함수로 작성된 실행문에서 더이상 실행할 로직이 없다면 return을 작성해주세요

2022-12-21 04:46 UTC, sangwoong03 requested changes

2022-12-21 04:46 UTC, sangwoong03 commented on kwanghwi/myapp/package.json
> +  }
package.json 파일의 dependencies와 devDependencies의 차이점을 학습해주세요!

- 개발 환경에서만 사용되는 패키지 모듈은 아래 명령어를 통해 프로젝트에 설치합니다.
`npm install --save-dev "module-name"`

- 반면, 배포 후에도 서버가 구동되기 위해 반드시 필요한 패키지 모듈은 다음과 같이 프로젝트에 설치합니다.
`npm install "module-name"`

- morgan이라는 모듈은 개발 단계에서 log를 확인할 수 있는 모듈기 떄문에 devDependencies에 추가해주는 것이 더 좋을 것 같습니다.

```suggestion
  "dependencies": {
    "cors": "^2.8.5",
    "dotenv": "^16.0.3",
    "express": "^4.18.2",
    "typeorm": "^0.3.11"
  },
  devDependencies: {
    "morgan": "^1.10.0"
  }
```

2022-12-21 04:59 UTC, Hwi227 commented on kwanghwi/myapp/package.json
> +  }
discussion수업할때 종범님께서 
log는 배포 이후에도 서버에서 확인해야하기 때문에 morgan을 dependencies에 둬야 한다고 말씀하셨던걸로 기억하고있는데, 
제가 잘못이해했던건지 확인해주시면 감사하겠습니다!

2022-12-21 05:34 UTC, sangwoong03 requested changes

2022-12-21 05:34 UTC, sangwoong03 commented on kwanghwi/myapp/package.json
> +  }
광휘님! 커멘트 감사해요.

배포 후에 백엔드 서버의 로그를 확인할 수 있는 부분은 다양한데요.

말씀하신 대로, morgan을 통해서 배포 후 로그를 확인할 수도 있습니다.

만약 morgan을 통해 배포 이후에도 서버의 로그를 계속 확인하고 싶다면 다음과 같이 적용해볼 수 있겠네요!
```
- package.json의 dependencies 부분에 morgan 추가.
- HTTP 통신을 시도하는 외부 IP 정보, 접속 시간, 통신 결과 등이 포함되어 있는 morgan 로그 option 지정
```

morgan이 제공하는 옵션을 확인해서 배포 이후에도 적용될 수 있도록 수정하면 될 것 같습니다ㅎㅎ

2022-12-21 07:50 UTC, sangwoong03 approved these changes
LGTM 👍

2022-12-21 07:50 UTC, merged