[41기 김광휘] Assignment (3, 4, 5, 6, 7, 8) - CRUD PR
wecode-bootcamp-korea/41-backend-westagram-2 pull request #10
Opened 2022-12-22 04:25 UTC by Hwi227

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [x] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- email, password를 이용한 로그인 기능 구현 (예시)

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- API 호출 시 필요한 값들에 대한 유효성 검사 (예시)

<br />

## :: 테스트 결과 이미지
1. Server가 잘 동작하는지 확인할 수 있는 Terminal 캡쳐 이미지
2. Postman(Client Tool)을 이용한 API 테스트 결과 이미지
3. DB 작업 PR인 경우 Table 생성 및 수정 결과에 대해 확인할 수 있는 이미지

<br />

## :: 기타 질문 및 특이 사항
- 제가 작성한 함수의 로직이 너무 복잡하다고 생각이 됩니다. 더 효율적인 방법이 없을까요? (예시)

2022-12-22 10:19 UTC, Jon9Beom commented
conflict 해결 후 다시 리뷰 봐드릴게요 광휘님 :)

2022-12-23 01:32 UTC, Jon9Beom commented on kwanghwi/myapp/app.js
> +app.post("/post/create", async (req, res) => {
```suggestion
app.post("/posts", async (req, res) => {
```
우리는 이미 http method를 통해 post(등록) 한다는 메세지를 잘 전달하고 있습니다. 
이처럼 무엇을 나타내는 what(게시글)과, 어떻게를 나타내는 how(등록)의 두가지를 엔드포인트와 http method를 통해 간단하고 명확하게 나타낼 수 있습니다. 마치 아래의 경우와 같이요!
```shell
http -v GET localhost:3000/users/1          # db의 유저들중 1번(/users/1)에 해당하는 유저의 정보의 가져와(GET)줘
``` 

이러한 방법으로 api endpoint를 작성하는 것을 RESTful한 api를 작성한다고 일컫고 있습니다. 이는 차주에 있을 Building RESTful APIs 세션에서 더 쉽고 재미있게 다룰 예정이니 참고해주세요-!

2022-12-23 01:32 UTC, Jon9Beom commented on kwanghwi/myapp/app.js
> +app.get("/posts/get", async (req, res) => {
```suggestion
app.get("/posts", async (req, res) => {
```

2022-12-23 01:32 UTC, Jon9Beom commented on kwanghwi/myapp/app.js
> +app.get("/post/get/:userId", async (req, res) => {
```suggestion
app.get("/users/:userId/posts", async (req, res) => {
```
해당 endpoint는 유저들 중, 특정 유저의, 게시글 목록을 불러오는 것 같네요! 맞다면 다음과 같이 수정되면 좋을 것 같습니다.

2022-12-23 01:32 UTC, Jon9Beom commented on kwanghwi/myapp/app.js
> +app.patch("/post/patch/", async (req, res) => {
```suggestion
app.patch("/post", async (req, res) => {
```

2022-12-23 01:32 UTC, Jon9Beom commented on kwanghwi/myapp/app.js
> +    `
.query() method안에 작성되는 SQL문을 완성하는 방법으로 두가지를 혼용하고 계십니다! 

### 리뷰 내용
typeorm의 initialize를 통해 만들어진 객체의 .query method에는 SQL 문이 들어갈 수 있습니다.

그 안에 작성되는 SQL 문에는 진주님이 작성해주신 것과 같이 자리 표시자(${ })를 통해 값을 넣을 수도, 혹은 제가 suggestion으로 작성드린 SQL 안에 ? 를 지정하여 동적으로 쿼리문이 수행될 수 있도록 하는 Placeholder를 사용하는 방법으로 값을 넣을 수도 있습니다.

두가지 방법 모두 다 SQL 안에 입력값을 넣어줄 수 있습니다.

다만 제가 작성한 것과 같이 ?를 활용하여 Placeholder를 사용하는 것을 지향해야 하는 이유는
보안적인 측면과 관련있습니다.

백엔드는 비단 클라이언트와 데이터베이스 사이의 접점이라고 볼 수 있는 API를 단순 동작하도록 구현하는 것 뿐만이 아닌, Data를 주고 받을 때, Database에서 원하는 data를 추출할 때를 포함한 여러 과정에서의 보안성도 고려해야 합니다.

해당 리뷰와 가장 관련이 있는 악성 공격으로는 SQL Injection 이라는 것이 있고 이는 정상적인 사용자가 아닌 누군가가 SQL문에 중요한 데이터를 추출할 수 있는 값을(ex. 항상 TRUE가 될 수 있는) 의도적으로 삽입 하여 data를 탈취하는 공격이고, ${}를 사용하면 이에 취약한 코드가 된다고 볼 수 있습니다.

따라서 가능하면 ?를 사용하고 placeholder를 통해 값을 넣어주는 방식으로 구현해주세요!

위와 관련된 [블로그 포스팅](https://www.veracode.com/blog/secure-development/how-prevent-sql-injection-nodejs)을 첨부해 드릴테니 읽어보시면 좋을 것 같습니다.

2022-12-23 01:32 UTC, Jon9Beom commented on kwanghwi/myapp/app.js
> +app.delete("/post/delete", async (req, res) => {
```suggestion
app.delete("/post", async (req, res) => {
```

2022-12-23 01:32 UTC, Jon9Beom commented on kwanghwi/myapp/app.js
> +  );
동일한 유저가 동일한 게시글에 대해 Like를 다회에 걸쳐 요청하면 어떻게 되나요?

2022-12-23 01:32 UTC, Jon9Beom commented on kwanghwi/myapp/app.js
> +    app.listen(3000, () => console.log(`server is listening on ${PORT}`));
PORT라는 이름의 변수에 할당하였던 것을 하드코딩으로 바꾼 이유가 있나요? 지금처럼 작성된다면 실제 서버는 다른 포트로 열려있지만, console.log()에는 엉뚱한 port number가 찍힐수도 있겠네요!

2022-12-23 01:32 UTC, Jon9Beom commented on kwanghwi/myapp/db/schema.sql
> +--
schema.sql은 Git으로 관리되지 않게 .gitignore에 추가해주시고 한번 git으로 Tracking되었던 것을 남겨두는 git cache도 삭제해주세요 :)

2022-12-23 08:42 UTC, Jon9Beom commented on kwanghwi/myapp/app.js
> +    );
문제 해결 능력이 좋네요 광휘님! 잘 작성해주셨습니다 :) 다만 이렇게 javascript 로직적으로 해결 할 수도 있지만 이런 경우에 가장 확실하면서도 간단하게 해결할 수 있는 방법은 likes 테이블에 (user_id, post_id)를 묶어서 UNIQUE 제약 조건을 거는 것입니다. 이를 통해 같은 유저가 같은 포스트에 대해 좋아요를 누르려 할 때 database단에서 이를 방지하게 됩니다.

2022-12-23 09:20 UTC, Hwi227 commented on kwanghwi/myapp/app.js
> +    );
<img width="1412" alt="스크린샷 2022-12-23 오후 6 18 43" src="https://user-images.githubusercontent.com/119113904/209308805-5e8a756d-a658-4e73-a462-d01b1f82095f.png">
2번째 과제에서 피드백받아서 이렇게 했었는데,
종범님께서 얘기해주신 내용과 위 스크린샷이 다른내용일까요??

2022-12-26 03:06 UTC, SeongJoon-K requested changes

2022-12-26 03:06 UTC, SeongJoon-K commented on kwanghwi/myapp/app.js
> +app.get("/users/:userId/posts", async (req, res) => {
해당 api는 path parameter 에서 userId로 받은 특정 유저가 작성한 글 목록을 불러오는 기능을 하는 것 같네요.
그렇다면 엔드포인트를 지금과 같이 `/posts/:userId` 보다 `/users/:userId/posts` 로 작성하는 것이 조금 더 자명한 엔드포인트를 만들 수 있을 것 같습니다.

아래의 예시 코드를 보면 조금 더 해당 리뷰의 내용이 와닿을 것 같네요-!
이렇듯 자명한 엔드포인트를 작성하는 것에 대해 REST하게 엔드포인트를 작성한다고 합니다.
해당 내용은 이후에 있을 RESTful API 세션에서 다뤄질 예정이니 참고해주세요 :)

```suggestion
// callback 방식의 비동기처리
app.get("/posts", (req, res) => {
    myDataSource.query(`SELECT * FROM users`,
      // 비동기 처리 이후에 실행되는 callback
      (err, data) => {res.status(200).json({ data: data })}
    );
});

// async와 await 방식의 비동기처리
app.get("/posts", async(req, res) => {
  const users = await myDataSource.query(`SELECT * FROM users`);
  
  res.status(200).json({ data : users})
});
```

2022-12-27 00:40 UTC, Jon9Beom commented
LGTM 👍

2022-12-27 00:40 UTC, merged