41기 이민규] Assignment 2 | Westagram Backend Project - 유저 회원가입 하기
wecode-bootcamp-korea/41-backend-westagram-2 pull request #13
Opened 2022-12-23 05:22 UTC by Minkku

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [x] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- user 가 회원가입시 입력하는 정보의 값을 DB에 저장

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- 스키마 내에 위스타그램 회원 정보를 저장할 users table 을 구축 후 npm start로 작동후 정상 구동이 되는지 확인
<br />

## :: 테스트 결과 이미지
1. Server가 잘 동작하는지 확인할 수 있는 Terminal 캡쳐 이미지
<img width="1167" alt="스크린샷 2022-12-23 오후 2 19 19" src="https://user-images.githubusercontent.com/97155555/209275916-c170a73d-4828-4172-aa84-1f6a66b3ed58.png">

<br />

## :: 기타 질문 및 특이 사항
- 동그라미 친 부분 값이 같아야지 동작하는게 맞을까요?
<img width="523" alt="스크린샷 2022-12-23 오후 2 20 42" src="https://user-images.githubusercontent.com/97155555/209276116-1c105dd2-8694-41b7-a6a7-3c2e051f4ee9.png">

2022-12-23 05:35 UTC, Minkku commented
질문했던거 답을 찾았습니다! 같은게 아니라 테이블을 생성했을때 테이블 명과 일치 하는거였군용!!

2022-12-23 08:50 UTC, Jon9Beom commented on minkyu/app.js
안녕하세요 민규님 :) ping 엔드포인트는 단순 서버의 상태를 체크하는 용도로 활용되는 health check api로 복수(s)를 붙이지 않아도 될 것 같습니다 ㅎㅎ 또한 이는 단순 pong이라는 메세지를 받는 것에 불과하기 때문에 등록이나 수정을 나타내는 status code인 201이 아닌 성공적으로 반환되었음을 의미하는 200이 더욱 어울릴 것 같네요!
```suggestion
app.get("/pings", (req,res) =>{
    res.status(200).json({"message" : "pong"});
});

```

2022-12-23 08:50 UTC, Jon9Beom commented on minkyu/app.js
> +    );
```suggestion
    await database.query(
        `INSERT INTO users(
            name,
            email,
            password
        ) VALUES (?, ?, ?);
        `,
        [ name, email, password ]
    );
```
우리가 인자로 넣어주는 값들은 name, email, password 3개 뿐인데 자리에 맞춰서 SQL코드에 값을 넣어주는 placeholder (`?`)는 4개를 작성해주셨네요! 하나는 지워주셔도 될 것 같습니다 :)

2022-12-23 08:50 UTC, Jon9Beom commented on minkyu/app.js
> +    const {title, content, user_id} = req.body;
```suggestion
    const {title, content, userId} = req.body;
```
javascript 에서는 snake_case가 아닌 camelCase를 사용하도록 해주세요-!

2022-12-23 08:50 UTC, Jon9Beom commented on minkyu/app.js
> +        [ title, content, user_id ]
```suggestion
        [ title, content, userId ]
```
위의 63번째 line에서 구조분해 할당 할 때에 userId로 수정되었으니 이에 맞춰 수정되어야겠습니다!

2022-12-23 08:50 UTC, Jon9Beom commented on minkyu/db/schema.sql
> +/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
schema.sql은 .gitignore에 추가하여 깃으로 관리되지 않게 해주시고, 이미 git으로 관리되고 있기 때문에 이후에 .gitignore에 추가 되어도 계속 github에 올라와 보이게 됩니다! 따라서 git cache도 같이 삭제해주세요~

2022-12-23 08:52 UTC, Minkku commented on minkyu/app.js
네 알겠습니다! 처음에는 "/ping" 으로 썼는데 오류가 계속 나서 바꿔서 동작해보고 오류 안 나는거 확인하고서 다시 바꾼다는걸 깜빡했어요!! 주의하도록 하겠습니다!

2022-12-26 03:11 UTC, SeongJoon-K requested changes
민규님 schema.sql 파일은 DB의 내부 로직이 담겨있는 파일입니다. 그렇기 때문에 외부에 노출되어선 안됩니다. 우선적으로 gitignore에 등록한 다음. github상의 캐시를 삭제하고 push 해 주세요!

1. gitignore에 `schema.sql` 추가
2. `git rm -rf --cached [파일명]`
3. add -> commit -> push 

위 단계를 진행 해 주시면 됩니다.

2022-12-26 03:11 UTC, SeongJoon-K commented on minkyu/app.js
> +
- import 순서 컨벤션에 맞게 수정해주세요! 사소한 부분이라 놓치기 쉽지만 처음 코드를 작성할 때부터 신경쓰고 작성하게 되면 추후에 관리하기도 용이하며 가독성도 좋아집니다.
- 다음과 같은 순서로 import 해줍니다.
    - Bulit-in 패키지
    - 3rd-party 패키지
    - custom 패키지
아래는 예시이니 참고해서 수정해 주세요. 
쓸데 없는 여백이 존재하지 않도록 하고 개발시 작성한 주석도 모두 지워주세요.
```suggestion
//// Built-in package
const http = require('http')

//// 3rd-party package
require('dotenv').config();
const express = require('express');
const cors    = require('cors');
const morgan  = require('morgan');
const { DataSource } = require('typeorm');

//custom package
const api = require('./../api')

const app = express();
```

2022-12-26 03:11 UTC, SeongJoon-K commented on minkyu/app.js
> +})
과제와 상관없거나 해당되지 않는 코드가 Push 되었습니다. 이후 과제에서 진행되는 코드는 그 과제에 맞는 PR에서 Push 해주세요.

2022-12-27 00:41 UTC, Jon9Beom commented
LGTM 👍

2022-12-27 00:41 UTC, merged