[김동규] Assignment 6 | Westagram Backend Project - CRUD
wecode-bootcamp-korea/41-backend-westagram-2 pull request #14
Opened 2022-12-25 08:10 UTC by pythakyu

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- 게시글 수정하기 기능 추가

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- 게시글 수정하기 기능 추가

<br />

## :: 테스트 결과 이미지
1. Server가 잘 동작하는지 확인할 수 있는 Terminal 캡쳐 이미지
2. Postman(Client Tool)을 이용한 API 테스트 결과 이미지
3. DB 작업 PR인 경우 Table 생성 및 수정 결과에 대해 확인할 수 있는 이미지
<img width="1512" alt="스크린샷 2022-12-25 오후 5 05 15" src="https://user-images.githubusercontent.com/119931360/209461151-2fc0b6ea-35e9-4d4c-b46d-a5d7f55e062f.png">

<br />

## :: 기타 질문 및 특이 사항

2022-12-26 03:15 UTC, SeongJoon-K requested changes
동규님 ! 너무 잘 해주셨습니다 ~ like post API 에 대한 피드백 참고해서 다시 수정해 주세요 ~

2022-12-26 03:15 UTC, SeongJoon-K commented on dongkyu/initial-settings-express/myapp/app.js
> +  })
- 좋아요 기능을 구현할 때에는 주의해야할 점이 있습니다.
- 하나의 사용자가 하나의 게시물에 대해서 좋아요를 할 수 있는 횟수는 단 한 번 이어야 합니다.
- 지금 구조에서는 좋아요를 누를 때마다 아래와 같이 likes 테이블에 계속해서 중복으로 데이터가 저장됩니다.
```suggestion
+----+---------+---------+---------------------+
| id | user_id | post_id | created_at          |
+----+---------+---------+---------------------+
|  1 |       1 |       3 | 2022-07-16 14:18:26 |
|  2 |       1 |       3 | 2022-07-16 14:18:26 |
|  3 |       1 |       3 | 2022-07-16 14:18:26 |
|  4 |       1 |       3 | 2022-07-16 14:18:26 |
|  5 |       1 |       3 | 2022-07-16 14:18:47 |
|  6 |       1 |       3 | 2022-07-16 14:18:47 |
+----+---------+---------+---------------------+
```

이를 막기 위해서, likes 테이블에 user_id와 post_id를 기준으로 UNIQUE 제약조건을 추가하는 migration 파일을 추가로 만들어서 올려주세요.

2022-12-27 01:05 UTC, Jon9Beom commented on dongkyu/initial-settings-express/myapp/app.js
> +      res.status(201).json({data: rows})
- 작성하신 코드에서 appDataSource.query()가 비동기적으로 실행되는 함수입니다.
- 비동기 처리를 하는 방법은 크게 callback, promise, async/await를 사용하는 방법이 있는데, 작성하신 코드에서는 이중에서 callback과 async/await를 혼합해서 사용하고 있습니다. 아래 예제를 참고해서 리펙토링해주세요.
    
    ```jsx
    // callback 방식의 비동기처리
    app.get("/posts", (req, res) => {
        myDataSource.query(`SELECT * FROM posts`,
          // 비동기 처리 이후에 실행되는 callback
          (err, data) => {res.status(200).json({ data: data })}
        );
    });
    
    // async와 await 방식의 비동기처리
    app.get("/posts", async(req, res) => {
      const posts = await myDataSource.query(`SELECT * FROM posts`);
      
      res.status(200).json({ data : posts})
    });
    
    ```
    
- JavaScript에서 비동기 처리할 수 있는 callback과 async/await 방식의 차이를 알고 싶다면, 아래 영상(드림코딩 Youtbue)을 참고해주세요.
[https://www.youtube.com/watch?v=aoQSOZfz3vQ](https://www.youtube.com/watch?v=aoQSOZfz3vQ)

</br>

--------------------

또한 postId도 자리표시자 `${}`대신 `?`를 통해 받을 수 있도록 수정해주시고 이유는 아래 추가로 달아드리는 코멘트를 확인해주세요 :)

### 리뷰 내용

typeorm의 initialize를 통해 만들어진 객체의 .query method에는 SQL 문이 들어갈 수 있습니다.

그 안에 작성되는 SQL 문에는 동규님이 작성해주신 것과 같이 자리 표시자(${ })를 통해 값을 넣을 수도, 혹은 제가 suggestion으로 작성드린 SQL 안에 ? 를 지정하여 동적으로 쿼리문이 수행될 수 있도록 하는 Placeholder를 사용하는 방법으로 값을 넣을 수도 있습니다.

두가지 방법 모두 다 SQL 안에 입력값을 넣어줄 수 있습니다.

다만 제가 작성한 것과 같이 ?를 활용하여 Placeholder를 사용하는 것을 지향해야 하는 이유는
보안적인 측면과 관련있습니다.

백엔드는 비단 클라이언트와 데이터베이스 사이의 접점이라고 볼 수 있는 API를 단순 동작하도록 구현하는 것 뿐만이 아닌, Data를 주고 받을 때, Database에서 원하는 data를 추출할 때를 포함한 여러 과정에서의 보안성도 고려해야 합니다.

해당 리뷰와 가장 관련이 있는 악성 공격으로는 SQL Injection 이라는 것이 있고 이는 정상적인 사용자가 아닌 누군가가 SQL문에 중요한 데이터를 추출할 수 있는 값을(ex. 항상 TRUE가 될 수 있는) 의도적으로 삽입 하여 data를 탈취하는 공격이고, ${}를 사용하면 이에 취약한 코드가 된다고 볼 수 있습니다.

따라서 가능하면 ?를 사용하고 placeholder를 통해 값을 넣어주는 방식으로 구현해주세요!

위와 관련된 [블로그 포스팅](https://www.veracode.com/blog/secure-development/how-prevent-sql-injection-nodejs)을 첨부해 드릴테니 읽어보시면 좋을 것 같습니다.

2022-12-27 09:49 UTC, Jon9Beom commented on dongkyu/initial-settings-express/myapp/app.js
> +});
작성하신 코드 대로라면 rows라는 변수를 선언해서 72번 line에서 작성해주신 결과 값을 담아주어야 response를 보내줄 수 있을 것 같습니다!

2022-12-27 09:49 UTC, Jon9Beom commented on dongkyu/initial-settings-express/myapp/app.js
> +  await appDataSource.query(
111번에서 `res.status(200).json({ data: rows });`로 작성하셨기에 다음과 같이 수정 되어야 합니다!
```suggestion
  const rows = await appDataSource.query(
```

2022-12-27 09:49 UTC, Jon9Beom commented on dongkyu/initial-settings-express/myapp/app.js
> +  );
```suggestion
  const rows = await appDataSource.query(
    `SELECT
        users.id as userId,
        users.name as userName,
        posts.id as postingId,
        posts.title as postingTitle,
        posts.content as postingContent
      FROM users
      JOIN posts
      ON users.id = posts.user_id AND posts.id = ?
      `,
    [postId]
  );
```

2022-12-27 09:49 UTC, Jon9Beom commented on dongkyu/initial-settings-express/myapp/app.js
> +app.get("/postings/:userId", async (req, res) => {
동규님~! 해당 API는 users 중, 특정 user의, posts 목록들을 가져오는 API이지요?
이런 경우에는 `/` 를 통해 계층 관계를 표현하면 조금 더 읽기 쉬운 엔드포인트가 될 수 있습니다.

해당 API는 users 중, 특정 user의, posts 목록들을 가져오는 API이지요?
위의 문구에서 `,`를 기준으로 나눠 말씀 드린 것 처럼 작성 한다면, 조금 더 쉽게 이해하실 수 있습니다.

```
# CASE 1. /users/:userId/posts
http -v GET localhost:3000/users/1/posts    # 서버의 유저들 중, 1번 유저의, 게시글들을 get(가져오는) 엔드포인트

# CASE 2./posts/:userId
http -v GET localhost:3000/posts/1          # 내가 의도한 건 CASE 1과 같지만 실제로 읽어지기로는 서버의 게시글들 중, 1번 게시글을 가져오는 엔드포인트 처럼 보임
```

차이가 조금 느껴지시나요?

이렇듯 자명한(그 자체만으로도 설명이 되는) 엔드포인트를 RESTful 하게 설계된 엔드포인트이자 API라고 말하는데, 이는 앞으로 있을 RESTful API 세션을 통해 한 번 더 자세하게 짚고 배워볼 예정이니, '이런식으로 엔드포인트를 작성하면 되는구나~' 라는 느낌만 가져가시면 될 것 같아요!

수정 부탁드립니다 :)

2022-12-28 02:24 UTC, Jon9Beom commented
LGTM 👍

2022-12-28 02:24 UTC, merged