[김용신] Assignment 2 | Westagram Backend Project - 유저 회원가입 하기
wecode-bootcamp-korea/41-backend-westagram-2 pull request #6
Opened 2022-12-21 06:22 UTC by kys0311

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- 유저 회원가입 기능 구현

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- 회원 가입 성공 시 회원가입 성공 메세지 출력

<br />

## :: 테스트 결과 이미지
![image](https://user-images.githubusercontent.com/41719506/208835714-2a5c81fe-fcc5-4608-8887-b214177afa41.png)

<br />

## :: 기타 질문 및 특이 사항

2022-12-21 09:24 UTC, sangwoong03 commented on yongshin/db/schema.sql
> +/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
schema.sql은 개별 로컬 환경에 따라 그 세부 내용이 다를 수 있으니 다른 개발자들과 함께 관리하는 순간 많은 에러를 낼 가능성이 있습니다. 해당 내용은 .gitignore에 추가하여서 GitHub에 올라오지 않도록 설정해 주세요.

이미 github 상에 push가 된 파일을 지우는 방법은 아래 명령어를 참고해주세요!
`git rm --cached "파일 경로"`

2022-12-21 09:24 UTC, sangwoong03 commented on yongshin/db/migrations/20221221055931_users.sql
> +	PRIMARY KEY(id));
동일한 유저 정보가 중복으로 저장되지 않도록 수정이 필요해보입니다~!
email 컬럼에 unique 속성을 추가해주세요!

2022-12-21 09:24 UTC, sangwoong03 commented on yongshin/db/migrations/20221221055952_likes.sql
> +	CONSTRAINT likes_post_id_fkey FOREIGN KEY (post_id) REFERENCES posts(id));
한명의 유저는 하나의 게시글에 2개 이상의 좋아요를 누를 수 없을 것입니다.

이에 맞는 unique 속성을 추가해주세요!

2022-12-21 09:24 UTC, sangwoong03 commented on yongshin/app.js
> +    const { name, email, profile_image, password } = req.body
자바스크립트는 camelCase를 통해 띄어쓰기를 구분하는 컨벤션이 있습니다.

데이터베이스의 컬럼을 작성하는 부분이 아니라면 camelCase로 통일할 수 있도록 수정해주세요!

```suggestion
    const { name, email, profileImage, password } = req.body
```

2022-12-26 03:02 UTC, SeongJoon-K requested changes
해당 피드백 참고해서 수정해 주세요 !

2022-12-26 03:02 UTC, SeongJoon-K commented on yongshin/app.js
> +dotenv.config();
- import 순서 컨벤션에 맞게 수정해주세요! 사소한 부분이라 놓치기 쉽지만 처음 코드를 작성할 때부터 신경쓰고 작성하게 되면 추후에 관리하기도 용이하며 가독성도 좋아집니다.
- 다음과 같은 순서로 import 해줍니다.
    - Bulit-in 패키지
    - 3rd-party 패키지
    - custom 패키지
아래는 예시이니 참고해서 작성해 주세요.
```suggestion
//// Built-in package
const http = require('http')

//// 3rd-party package
require('dotenv').config();
const express = require('express');
const cors    = require('cors');
const morgan  = require('morgan');
const { DataSource } = require('typeorm');

//custom package
const api = require('./../api')

const app = express();
```

2022-12-27 00:37 UTC, Jon9Beom commented
LGTM 👍

2022-12-27 00:37 UTC, merged